version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
      args:
        - http-proxy=http://165.225.76.38:80/
        - https_proxy=http://165.225.76.38:80/
    ports: 
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
      args:
        - http-proxy=http://165.225.76.38:80/
        - https_proxy=http://165.225.76.38:80/
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - '500:500'
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
      args:
        - http-proxy=http://165.225.76.38:80/
        - https_proxy=http://165.225.76.38:80/
    volumes:
      - /app/nodes_modules
      - ./client:/app
    ports:
      - '3000:3000'
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
      args:
        - http-proxy=http://165.225.76.38:80/
        - https_proxy=http://165.225.76.38:80/
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379